# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractActivity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('operation', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'abstractactivity',
            },
        ),
        migrations.CreateModel(
            name='AbstractWorkflow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'abstractworkflow',
            },
        ),
        migrations.CreateModel(
            name='AbstractWorkflowDependency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'abstractworkflowdependency',
            },
        ),
        migrations.CreateModel(
            name='Concreteactivity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('operation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'concreteactivity',
            },
        ),
        migrations.CreateModel(
            name='Concreteworkflow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'concreteworkflow',
            },
        ),
        migrations.CreateModel(
            name='Derivation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('abstractActivity', models.ForeignKey(blank=True, db_column='abstractactivityid', null=True, on_delete=django.db.models.deletion.CASCADE, to='addline.AbstractActivity')),
                ('abstractWorkflow', models.ForeignKey(blank=True, db_column='abstractworkflowid', null=True, on_delete=django.db.models.deletion.CASCADE, to='addline.AbstractWorkflow')),
            ],
            options={
                'db_table': 'derivation',
            },
        ),
        migrations.CreateModel(
            name='ExpLine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'expline',
            },
        ),
        migrations.CreateModel(
            name='ExpLineActDependency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('variant', models.NullBooleanField()),
                ('optional', models.NullBooleanField()),
            ],
            options={
                'db_table': 'explineactdependency',
            },
        ),
        migrations.CreateModel(
            name='ExpLineActivity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('operation', models.CharField(blank=True, max_length=255, null=True)),
                ('variant', models.NullBooleanField()),
                ('optional', models.NullBooleanField()),
                ('expLine', models.ForeignKey(blank=True, db_column='explineid', null=True, on_delete=django.db.models.deletion.CASCADE, to='addline.ExpLine')),
            ],
            options={
                'db_table': 'explineactivity',
            },
        ),
        migrations.CreateModel(
            name='Instantiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstractActivity', models.ForeignKey(blank=True, db_column='abstractactivityid', null=True, on_delete=django.db.models.deletion.CASCADE, to='addline.AbstractActivity')),
                ('abstractWorkflow', models.ForeignKey(blank=True, db_column='abstractworkflowid', null=True, on_delete=django.db.models.deletion.CASCADE, to='addline.AbstractWorkflow')),
                ('concreteActivity', models.ForeignKey(blank=True, db_column='concreteactivityid', null=True, on_delete=django.db.models.deletion.CASCADE, to='addline.Concreteactivity')),
                ('concreteWorkflow', models.ForeignKey(blank=True, db_column='concreteworkflowid', null=True, on_delete=django.db.models.deletion.CASCADE, to='addline.Concreteworkflow')),
            ],
            options={
                'db_table': 'instantiation',
            },
        ),
        migrations.AddField(
            model_name='explineactdependency',
            name='ELActivity',
            field=models.ForeignKey(blank=True, db_column='explineactid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ELActivity', to='addline.ExpLineActivity'),
        ),
        migrations.AddField(
            model_name='explineactdependency',
            name='dependentELActivity',
            field=models.ForeignKey(blank=True, db_column='depexplineactid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependentELActivity', to='addline.ExpLineActivity'),
        ),
        migrations.AddField(
            model_name='derivation',
            name='expLineActivity',
            field=models.ForeignKey(blank=True, db_column='explineactid', null=True, on_delete=django.db.models.deletion.CASCADE, to='addline.ExpLineActivity'),
        ),
        migrations.AddField(
            model_name='concreteactivity',
            name='concreteWorkflow',
            field=models.ForeignKey(blank=True, db_column='concreteworkflowid', null=True, on_delete=django.db.models.deletion.CASCADE, to='addline.Concreteworkflow'),
        ),
        migrations.AddField(
            model_name='abstractworkflowdependency',
            name='activity',
            field=models.ForeignKey(blank=True, db_column='derivationid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derivationid', to='addline.Derivation'),
        ),
        migrations.AddField(
            model_name='abstractworkflowdependency',
            name='dependentActivity',
            field=models.ForeignKey(blank=True, db_column='depderivationid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depderivationid', to='addline.Derivation'),
        ),
    ]
