# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivation',
            name='expLine',
            field=models.ForeignKey(blank=True, db_column='explineid', null=True, on_delete=django.db.models.deletion.CASCADE, to='addline.ExpLine'),
        ),
        migrations.AddField(
            model_name='explineactdependency',
            name='expLine',
            field=models.ForeignKey(blank=True, db_column='explineid', null=True, on_delete=django.db.models.deletion.CASCADE, to='addline.ExpLine'),
        ),
    ]
