# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addline', '0004_abstractworkflowdependency_expline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractworkflowdependency',
            name='expLine',
        ),
        migrations.RemoveField(
            model_name='derivation',
            name='expLine',
        ),
        migrations.AddField(
            model_name='abstractworkflowdependency',
            name='ELActivity',
            field=models.ForeignKey(blank=True, db_column='explineactid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExpLineActivity', to='addline.ExpLineActivity'),
        ),
    ]
