# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addline', '0006_remove_explineactdependency_expline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractworkflowdependency',
            name='ELActivity',
        ),
    ]
