# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addline', '0008_auto_20161020_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractactivity',
            name='operation',
            field=models.CharField(blank=True, choices=[(1, 'Map'), (2, 'SplitMap'), (3, 'Query'), (4, 'Reduce'), (5, 'Filter')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='concreteactivity',
            name='operation',
            field=models.CharField(blank=True, choices=[(1, 'Map'), (2, 'SplitMap'), (3, 'Query'), (4, 'Reduce'), (5, 'Filter')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='explineactdependency',
            name='optional',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='explineactdependency',
            name='variant',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='explineactivity',
            name='operation',
            field=models.CharField(blank=True, choices=[(1, 'Map'), (2, 'SplitMap'), (3, 'Query'), (4, 'Reduce'), (5, 'Filter')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='explineactivity',
            name='optional',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='explineactivity',
            name='variant',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
