# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addline', '0009_auto_20161021_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explineactdependency',
            name='ELActivity',
        ),
        migrations.AddField(
            model_name='explineactdependency',
            name='eLActivity',
            field=models.ForeignKey(blank=True, db_column='explineactid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eLActivity', to='addline.ExpLineActivity'),
        ),
    ]
